// Country code type definition
type CountryCode = {
  id: string;
  label: string;
  value: string;
};

export const countryCodes: CountryCode[] = [
  { id: "af", label: "Afghanistan", value: "+93" },
  { id: "al", label: "Albania", value: "+355" },
  { id: "dz", label: "Algeria", value: "+213" },
  { id: "as", label: "American Samoa", value: "+1-684" },
  { id: "ad", label: "Andorra", value: "+376" },
  { id: "ao", label: "Angola", value: "+244" },
  { id: "ai", label: "Anguilla", value: "+1-264" },
  { id: "aq", label: "Antarctica", value: "+672" },
  { id: "ag", label: "Antigua and Barbuda", value: "+1-268" },
  { id: "ar", label: "Argentina", value: "+54" },
  { id: "am", label: "Armenia", value: "+374" },
  { id: "aw", label: "Aruba", value: "+297" },
  { id: "au", label: "Australia", value: "+61" },
  { id: "at", label: "Austria", value: "+43" },
  { id: "az", label: "Azerbaijan", value: "+994" },
  { id: "bs", label: "Bahamas", value: "+1-242" },
  { id: "bh", label: "Bahrain", value: "+973" },
  { id: "bd", label: "Bangladesh", value: "+880" },
  { id: "bb", label: "Barbados", value: "+1-246" },
  { id: "by", label: "Belarus", value: "+375" },
  { id: "be", label: "Belgium", value: "+32" },
  { id: "bz", label: "Belize", value: "+501" },
  { id: "bj", label: "Benin", value: "+229" },
  { id: "bm", label: "Bermuda", value: "+1-441" },
  { id: "bt", label: "Bhutan", value: "+975" },
  { id: "bo", label: "Bolivia", value: "+591" },
  { id: "ba", label: "Bosnia and Herzegovina", value: "+387" },
  { id: "bw", label: "Botswana", value: "+267" },
  { id: "br", label: "Brazil", value: "+55" },
  { id: "io", label: "British Indian Ocean Territory", value: "+246" },
  { id: "vg", label: "British Virgin Islands", value: "+1-284" },
  { id: "bn", label: "Brunei", value: "+673" },
  { id: "bg", label: "Bulgaria", value: "+359" },
  { id: "bf", label: "Burkina Faso", value: "+226" },
  { id: "bi", label: "Burundi", value: "+257" },
  { id: "kh", label: "Cambodia", value: "+855" },
  { id: "cm", label: "Cameroon", value: "+237" },
  { id: "ca", label: "Canada", value: "+1" },
  { id: "cv", label: "Cape Verde", value: "+238" },
  { id: "ky", label: "Cayman Islands", value: "+1-345" },
  { id: "cf", label: "Central African Republic", value: "+236" },
  { id: "td", label: "Chad", value: "+235" },
  { id: "cl", label: "Chile", value: "+56" },
  { id: "cn", label: "China", value: "+86" },
  { id: "cx", label: "Christmas Island", value: "+61" },
  { id: "cc", label: "Cocos Islands", value: "+61" },
  { id: "co", label: "Colombia", value: "+57" },
  { id: "km", label: "Comoros", value: "+269" },
  { id: "ck", label: "Cook Islands", value: "+682" },
  { id: "cr", label: "Costa Rica", value: "+506" },
  { id: "hr", label: "Croatia", value: "+385" },
  { id: "cu", label: "Cuba", value: "+53" },
  { id: "cw", label: "Curacao", value: "+599" },
  { id: "cy", label: "Cyprus", value: "+357" },
  { id: "cz", label: "Czech Republic", value: "+420" },
  { id: "cd", label: "Democratic Republic of the Congo", value: "+243" },
  { id: "dk", label: "Denmark", value: "+45" },
  { id: "dj", label: "Djibouti", value: "+253" },
  { id: "dm", label: "Dominica", value: "+1-767" },
  { id: "do", label: "Dominican Republic", value: "+1-809" },
  { id: "tl", label: "East Timor", value: "+670" },
  { id: "ec", label: "Ecuador", value: "+593" },
  { id: "eg", label: "Egypt", value: "+20" },
  { id: "sv", label: "El Salvador", value: "+503" },
  { id: "gq", label: "Equatorial Guinea", value: "+240" },
  { id: "er", label: "Eritrea", value: "+291" },
  { id: "ee", label: "Estonia", value: "+372" },
  { id: "et", label: "Ethiopia", value: "+251" },
  { id: "fk", label: "Falkland Islands", value: "+500" },
  { id: "fo", label: "Faroe Islands", value: "+298" },
  { id: "fj", label: "Fiji", value: "+679" },
  { id: "fi", label: "Finland", value: "+358" },
  { id: "fr", label: "France", value: "+33" },
  { id: "pf", label: "French Polynesia", value: "+689" },
  { id: "ga", label: "Gabon", value: "+241" },
  { id: "gm", label: "Gambia", value: "+220" },
  { id: "ge", label: "Georgia", value: "+995" },
  { id: "de", label: "Germany", value: "+49" },
  { id: "gh", label: "Ghana", value: "+233" },
  { id: "gi", label: "Gibraltar", value: "+350" },
  { id: "gr", label: "Greece", value: "+30" },
  { id: "gl", label: "Greenland", value: "+299" },
  { id: "gd", label: "Grenada", value: "+1-473" },
  { id: "gu", label: "Guam", value: "+1-671" },
  { id: "gt", label: "Guatemala", value: "+502" },
  { id: "gg", label: "Guernsey", value: "+44-1481" },
  { id: "gn", label: "Guinea", value: "+224" },
  { id: "gw", label: "Guinea-Bissau", value: "+245" },
  { id: "gy", label: "Guyana", value: "+592" },
  { id: "ht", label: "Haiti", value: "+509" },
  { id: "hn", label: "Honduras", value: "+504" },
  { id: "hk", label: "Hong Kong", value: "+852" },
  { id: "hu", label: "Hungary", value: "+36" },
  { id: "is", label: "Iceland", value: "+354" },
  { id: "in", label: "India", value: "+91" },
  { id: "id", label: "Indonesia", value: "+62" },
  { id: "ir", label: "Iran", value: "+98" },
  { id: "iq", label: "Iraq", value: "+964" },
  { id: "ie", label: "Ireland", value: "+353" },
  { id: "im", label: "Isle of Man", value: "+44-1624" },
  { id: "il", label: "Israel", value: "+972" },
  { id: "it", label: "Italy", value: "+39" },
  { id: "ci", label: "Ivory Coast", value: "+225" },
  { id: "jm", label: "Jamaica", value: "+1-876" },
  { id: "jp", label: "Japan", value: "+81" },
  { id: "je", label: "Jersey", value: "+44-1534" },
  { id: "jo", label: "Jordan", value: "+962" },
  { id: "kz", label: "Kazakhstan", value: "+7" },
  { id: "ke", label: "Kenya", value: "+254" },
  { id: "ki", label: "Kiribati", value: "+686" },
  { id: "xk", label: "Kosovo", value: "+383" },
  { id: "kw", label: "Kuwait", value: "+965" },
  { id: "kg", label: "Kyrgyzstan", value: "+996" },
  { id: "la", label: "Laos", value: "+856" },
  { id: "lv", label: "Latvia", value: "+371" },
  { id: "lb", label: "Lebanon", value: "+961" },
  { id: "ls", label: "Lesotho", value: "+266" },
  { id: "lr", label: "Liberia", value: "+231" },
  { id: "ly", label: "Libya", value: "+218" },
  { id: "li", label: "Liechtenstein", value: "+423" },
  { id: "lt", label: "Lithuania", value: "+370" },
  { id: "lu", label: "Luxembourg", value: "+352" },
  { id: "mo", label: "Macao", value: "+853" },
  { id: "mk", label: "Macedonia", value: "+389" },
  { id: "mg", label: "Madagascar", value: "+261" },
  { id: "mw", label: "Malawi", value: "+265" },
  { id: "my", label: "Malaysia", value: "+60" },
  { id: "mv", label: "Maldives", value: "+960" },
  { id: "ml", label: "Mali", value: "+223" },
  { id: "mt", label: "Malta", value: "+356" },
  { id: "mh", label: "Marshall Islands", value: "+692" },
  { id: "mr", label: "Mauritania", value: "+222" },
  { id: "mu", label: "Mauritius", value: "+230" },
  { id: "yt", label: "Mayotte", value: "+262" },
  { id: "mx", label: "Mexico", value: "+52" },
  { id: "fm", label: "Micronesia", value: "+691" },
  { id: "md", label: "Moldova", value: "+373" },
  { id: "mc", label: "Monaco", value: "+377" },
  { id: "mn", label: "Mongolia", value: "+976" },
  { id: "me", label: "Montenegro", value: "+382" },
  { id: "ms", label: "Montserrat", value: "+1-664" },
  { id: "ma", label: "Morocco", value: "+212" },
  { id: "mz", label: "Mozambique", value: "+258" },
  { id: "mm", label: "Myanmar", value: "+95" },
  { id: "na", label: "Namibia", value: "+264" },
  { id: "nr", label: "Nauru", value: "+674" },
  { id: "np", label: "Nepal", value: "+977" },
  { id: "nl", label: "Netherlands", value: "+31" },
  { id: "an", label: "Netherlands Antilles", value: "+599" },
  { id: "nc", label: "New Caledonia", value: "+687" },
  { id: "nz", label: "New Zealand", value: "+64" },
  { id: "ni", label: "Nicaragua", value: "+505" },
  { id: "ne", label: "Niger", value: "+227" },
  { id: "ng", label: "Nigeria", value: "+234" },
  { id: "nu", label: "Niue", value: "+683" },
  { id: "kp", label: "North Korea", value: "+850" },
  { id: "mp", label: "Northern Mariana Islands", value: "+1-670" },
  { id: "no", label: "Norway", value: "+47" },
  { id: "om", label: "Oman", value: "+968" },
  { id: "pk", label: "Pakistan", value: "+92" },
  { id: "pw", label: "Palau", value: "+680" },
  { id: "ps", label: "Palestine", value: "+970" },
  { id: "pa", label: "Panama", value: "+507" },
  { id: "pg", label: "Papua New Guinea", value: "+675" },
  { id: "py", label: "Paraguay", value: "+595" },
  { id: "pe", label: "Peru", value: "+51" },
  { id: "ph", label: "Philippines", value: "+63" },
  { id: "pn", label: "Pitcairn", value: "+64" },
  { id: "pl", label: "Poland", value: "+48" },
  { id: "pt", label: "Portugal", value: "+351" },
  { id: "pr", label: "Puerto Rico", value: "+1-787" },
  { id: "qa", label: "Qatar", value: "+974" },
  { id: "cg", label: "Republic of the Congo", value: "+242" },
  { id: "re", label: "Reunion", value: "+262" },
  { id: "ro", label: "Romania", value: "+40" },
  { id: "ru", label: "Russia", value: "+7" },
  { id: "rw", label: "Rwanda", value: "+250" },
  { id: "bl", label: "Saint Barthelemy", value: "+590" },
  { id: "sh", label: "Saint Helena", value: "+290" },
  { id: "kn", label: "Saint Kitts and Nevis", value: "+1-869" },
  { id: "lc", label: "Saint Lucia", value: "+1-758" },
  { id: "mf", label: "Saint Martin", value: "+590" },
  { id: "pm", label: "Saint Pierre and Miquelon", value: "+508" },
  { id: "vc", label: "Saint Vincent and the Grenadines", value: "+1-784" },
  { id: "ws", label: "Samoa", value: "+685" },
  { id: "sm", label: "San Marino", value: "+378" },
  { id: "st", label: "Sao Tome and Principe", value: "+239" },
  { id: "sa", label: "Saudi Arabia", value: "+966" },
  { id: "sn", label: "Senegal", value: "+221" },
  { id: "rs", label: "Serbia", value: "+381" },
  { id: "sc", label: "Seychelles", value: "+248" },
  { id: "sl", label: "Sierra Leone", value: "+232" },
  { id: "sg", label: "Singapore", value: "+65" },
  { id: "sx", label: "Sint Maarten", value: "+1-721" },
  { id: "sk", label: "Slovakia", value: "+421" },
  { id: "si", label: "Slovenia", value: "+386" },
  { id: "sb", label: "Solomon Islands", value: "+677" },
  { id: "so", label: "Somalia", value: "+252" },
  { id: "za", label: "South Africa", value: "+27" },
  { id: "kr", label: "South Korea", value: "+82" },
  { id: "ss", label: "South Sudan", value: "+211" },
  { id: "es", label: "Spain", value: "+34" },
  { id: "lk", label: "Sri Lanka", value: "+94" },
  { id: "sd", label: "Sudan", value: "+249" },
  { id: "sr", label: "Suriname", value: "+597" },
  { id: "sj", label: "Svalbard and Jan Mayen", value: "+47" },
  { id: "sz", label: "Swaziland", value: "+268" },
  { id: "se", label: "Sweden", value: "+46" },
  { id: "ch", label: "Switzerland", value: "+41" },
  { id: "sy", label: "Syria", value: "+963" },
  { id: "tw", label: "Taiwan", value: "+886" },
  { id: "tj", label: "Tajikistan", value: "+992" },
  { id: "tz", label: "Tanzania", value: "+255" },
  { id: "th", label: "Thailand", value: "+66" },
  { id: "tg", label: "Togo", value: "+228" },
  { id: "tk", label: "Tokelau", value: "+690" },
  { id: "to", label: "Tonga", value: "+676" },
  { id: "tt", label: "Trinidad and Tobago", value: "+1-868" },
  { id: "tn", label: "Tunisia", value: "+216" },
  { id: "tr", label: "Turkey", value: "+90" },
  { id: "tm", label: "Turkmenistan", value: "+993" },
  { id: "tc", label: "Turks and Caicos Islands", value: "+1-649" },
  { id: "tv", label: "Tuvalu", value: "+688" },
  { id: "vi", label: "U.S. Virgin Islands", value: "+1-340" },
  { id: "ug", label: "Uganda", value: "+256" },
  { id: "ua", label: "Ukraine", value: "+380" },
  { id: "ae", label: "United Arab Emirates", value: "+971" },
  { id: "gb", label: "United Kingdom", value: "+44" },
  { id: "us", label: "United States", value: "+1" },
  { id: "uy", label: "Uruguay", value: "+598" },
  { id: "uz", label: "Uzbekistan", value: "+998" },
  { id: "vu", label: "Vanuatu", value: "+678" },
  { id: "va", label: "Vatican", value: "+379" },
  { id: "ve", label: "Venezuela", value: "+58" },
  { id: "vn", label: "Vietnam", value: "+84" },
  { id: "wf", label: "Wallis and Futuna", value: "+681" },
  { id: "eh", label: "Western Sahara", value: "+212" },
  { id: "ye", label: "Yemen", value: "+967" },
  { id: "zm", label: "Zambia", value: "+260" },
  { id: "zw", label: "Zimbabwe", value: "+263" },
];
